[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_APP_URL = "https://timeshare.epublicsf.org"
  VITE_SUPABASE_URL = "https://lbqhvgvvxvrrooalywhz.supabase.co"
  # Note: Add other environment variables through the Netlify UI for security 